language: node_js
node_js:
- "8.4.0"
sudo: required
cache:
  directories:
    - node_modules
before_install:
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
- npm i -D uglifyjs-webpack-plugin
install:
- npm install
- npm run ng-deploy
- ls -l
- docker build -t saksit32/se234-lab10-client .
- docker push saksit32/se234-lab10-client
script: 
- docker-compose -H "$DOCKER_HOST" up -d

service: docker